GRANT EXECUTE ON FUNCTION _fill_cvtermpath4node(integer, integer, integer, integer, integer)  TO chacrm_execute;
GRANT EXECUTE ON FUNCTION _fill_cvtermpath4node2detect_cycle(integer, integer, integer, integer, integer)  TO chacrm_execute;
GRANT EXECUTE ON FUNCTION _fill_cvtermpath4root(integer, integer)  TO chacrm_execute;
GRANT EXECUTE ON FUNCTION _fill_cvtermpath4root2detect_cycle(integer, integer)  TO chacrm_execute;
GRANT EXECUTE ON FUNCTION _fill_cvtermpath4soi(integer, integer)  TO chacrm_execute;
GRANT EXECUTE ON FUNCTION _fill_cvtermpath4soinode(integer, integer, integer, integer, integer)  TO chacrm_execute;
GRANT EXECUTE ON FUNCTION _get_all_object_ids(integer)  TO chacrm_execute;
GRANT EXECUTE ON FUNCTION _get_all_subject_ids(integer)  TO chacrm_execute;
GRANT EXECUTE ON FUNCTION boxquery(integer, integer)  TO chacrm_execute;
GRANT EXECUTE ON FUNCTION boxrange(integer, integer)  TO chacrm_execute;
GRANT EXECUTE ON FUNCTION cache_all_fragment_residues()  TO chacrm_execute;
GRANT EXECUTE ON FUNCTION cache_all_fragment_residues(integer)  TO chacrm_execute;
GRANT EXECUTE ON FUNCTION chado_args_init()  TO chacrm_execute;
GRANT EXECUTE ON FUNCTION complement_residues(text)  TO chacrm_execute;
GRANT EXECUTE ON FUNCTION concat_pair(text, text)  TO chacrm_execute;
GRANT EXECUTE ON FUNCTION create_point(integer, integer)  TO chacrm_execute;
GRANT EXECUTE ON FUNCTION create_soi()  TO chacrm_execute;
GRANT EXECUTE ON FUNCTION delete_analysis_features(integer, integer)  TO chacrm_execute;
GRANT EXECUTE ON FUNCTION feature_disjoint_from(integer)  TO chacrm_execute;
GRANT EXECUTE ON FUNCTION feature_intersecting(integer)  TO chacrm_execute;
GRANT EXECUTE ON FUNCTION feature_overlaps(integer)  TO chacrm_execute;
GRANT EXECUTE ON FUNCTION feature_slice(integer, integer)  TO chacrm_execute;
GRANT EXECUTE ON FUNCTION feature_slice(character varying, integer, integer)  TO chacrm_execute;
GRANT EXECUTE ON FUNCTION feature_slice(integer, integer, integer)  TO chacrm_execute;
GRANT EXECUTE ON FUNCTION feature_subalignments(integer) TO chacrm_execute;
GRANT EXECUTE ON FUNCTION featureloc_slice(character varying, integer, integer) TO chacrm_execute;
GRANT EXECUTE ON FUNCTION featureloc_slice(integer, integer, integer) TO chacrm_execute;
GRANT EXECUTE ON FUNCTION featureloc_slice(integer, integer) TO chacrm_execute;
GRANT EXECUTE ON FUNCTION featureslice(integer, integer) TO chacrm_execute;
GRANT EXECUTE ON FUNCTION fill_cvtermpath(integer)  TO chacrm_execute;
GRANT EXECUTE ON FUNCTION fill_cvtermpath(character varying)  TO chacrm_execute;
GRANT EXECUTE ON FUNCTION foo(integer)  TO chacrm_execute;
GRANT EXECUTE ON FUNCTION get_all_object_ids(integer)  TO chacrm_execute;
GRANT EXECUTE ON FUNCTION get_all_subject_ids(integer)  TO chacrm_execute;
GRANT EXECUTE ON FUNCTION get_cv_id_for_feature()  TO chacrm_execute;
GRANT EXECUTE ON FUNCTION get_cv_id_for_feature_relationsgip()  TO chacrm_execute;
GRANT EXECUTE ON FUNCTION get_cv_id_for_feature_relationship()  TO chacrm_execute;
GRANT EXECUTE ON FUNCTION get_cv_id_for_featureprop()  TO chacrm_execute;
GRANT EXECUTE ON FUNCTION get_cv_id_for_relation()  TO chacrm_execute;
GRANT EXECUTE ON FUNCTION get_cvterm_id_for_is_a()  TO chacrm_execute;
GRANT EXECUTE ON FUNCTION get_cycle_cvterm_id(integer, integer)  TO chacrm_execute;
GRANT EXECUTE ON FUNCTION get_cycle_cvterm_id(integer)  TO chacrm_execute;
GRANT EXECUTE ON FUNCTION get_cycle_cvterm_id(character varying)  TO chacrm_execute;
GRANT EXECUTE ON FUNCTION get_cycle_cvterm_ids(integer)  TO chacrm_execute;
GRANT EXECUTE ON FUNCTION get_feature_id(character varying, character varying, character varying)  TO chacrm_execute;
GRANT EXECUTE ON FUNCTION get_feature_ids(text)  TO chacrm_execute;
GRANT EXECUTE ON FUNCTION get_feature_ids_by_child_count(character varying, character varying, integer, character varying, character)  TO chacrm_execute;
GRANT EXECUTE ON FUNCTION get_feature_ids_by_ont(character varying, character varying)  TO chacrm_execute;
GRANT EXECUTE ON FUNCTION get_feature_ids_by_ont_root(character varying, character varying)  TO chacrm_execute;
GRANT EXECUTE ON FUNCTION get_feature_ids_by_property(character varying, character varying)  TO chacrm_execute;
GRANT EXECUTE ON FUNCTION get_feature_ids_by_propval(character varying)  TO chacrm_execute;
GRANT EXECUTE ON FUNCTION get_feature_ids_by_type(character varying, character)  TO chacrm_execute;
GRANT EXECUTE ON FUNCTION get_feature_ids_by_type_name(character varying, text, character)  TO chacrm_execute;
GRANT EXECUTE ON FUNCTION get_feature_ids_by_type_src(character varying, text, character)  TO chacrm_execute;
GRANT EXECUTE ON FUNCTION get_feature_relationship_type_id(character varying)  TO chacrm_execute;
GRANT EXECUTE ON FUNCTION get_feature_type_id(character varying)  TO chacrm_execute;
GRANT EXECUTE ON FUNCTION get_featureprop_type_id(character varying)  TO chacrm_execute;
GRANT EXECUTE ON FUNCTION get_gene_synonyms(text)  TO chacrm_execute;
GRANT EXECUTE ON FUNCTION get_graph_above(integer)  TO chacrm_execute;
GRANT EXECUTE ON FUNCTION get_graph_below(integer)  TO chacrm_execute;
GRANT EXECUTE ON FUNCTION get_it_sub_cvterm_ids(text)  TO chacrm_execute;
GRANT EXECUTE ON FUNCTION get_organism_id(character varying, character varying)  TO chacrm_execute;
GRANT EXECUTE ON FUNCTION get_organism_id(character varying)  TO chacrm_execute;
GRANT EXECUTE ON FUNCTION get_organism_id_abbrev(character varying)  TO chacrm_execute;
GRANT EXECUTE ON FUNCTION get_sub_feature_ids(text)  TO chacrm_execute;
GRANT EXECUTE ON FUNCTION get_sub_feature_ids(integer)  TO chacrm_execute;
GRANT EXECUTE ON FUNCTION get_sub_feature_ids(integer, integer)  TO chacrm_execute;
GRANT EXECUTE ON FUNCTION get_sub_feature_ids_by_type_src(character varying, text, character)  TO chacrm_execute;
GRANT EXECUTE ON FUNCTION get_up_feature_ids(text)  TO chacrm_execute;
GRANT EXECUTE ON FUNCTION get_up_feature_ids(integer)  TO chacrm_execute;
GRANT EXECUTE ON FUNCTION get_up_feature_ids(integer, integer)  TO chacrm_execute;
GRANT EXECUTE ON FUNCTION p(integer, integer)  TO chacrm_execute;
GRANT EXECUTE ON FUNCTION plpgsql_call_handler()  TO chacrm_execute;
GRANT EXECUTE ON FUNCTION project_featureloc_up(integer, integer)  TO chacrm_execute;
GRANT EXECUTE ON FUNCTION project_point_down(integer, integer, integer, integer)  TO chacrm_execute;
GRANT EXECUTE ON FUNCTION project_point_up(integer, integer, integer, integer)  TO chacrm_execute;
GRANT EXECUTE ON FUNCTION remove_transformant_image_location(character varying, character varying)  TO chacrm_execute;
GRANT EXECUTE ON FUNCTION reverse_complement(text)  TO chacrm_execute;
GRANT EXECUTE ON FUNCTION reverse_string(text)  TO chacrm_execute;
GRANT EXECUTE ON FUNCTION store_analysis(character varying, character varying, character varying)  TO chacrm_execute;
GRANT EXECUTE ON FUNCTION store_analysisfeature(integer, integer, integer, integer, integer, integer, character varying, character varying, integer, boolean, integer, double precision, double precision, double precision, double precision)  TO chacrm_execute;
GRANT EXECUTE ON FUNCTION store_db(character varying)  TO chacrm_execute;
GRANT EXECUTE ON FUNCTION store_dbxref(character varying, character varying)  TO chacrm_execute;
GRANT EXECUTE ON FUNCTION store_feature(integer, integer, integer, integer, integer, integer, character varying, character varying, integer, boolean)  TO chacrm_execute;
GRANT EXECUTE ON FUNCTION store_feature_dbxref(integer, character varying, character varying)  TO chacrm_execute;
GRANT EXECUTE ON FUNCTION store_feature_synonym(integer, character varying, integer, boolean, boolean, integer)  TO chacrm_execute;
GRANT EXECUTE ON FUNCTION store_featureloc(integer, integer, integer, integer, integer, integer, integer)  TO chacrm_execute;
GRANT EXECUTE ON FUNCTION store_featureprop(integer, character varying, character varying)  TO chacrm_execute;
GRANT EXECUTE ON FUNCTION store_featureprop(integer, character varying, character varying, integer)  TO chacrm_execute;
GRANT EXECUTE ON FUNCTION store_featureprop(character varying, character varying, integer)  TO chacrm_execute;
GRANT EXECUTE ON FUNCTION store_organism(character varying, character varying)  TO chacrm_execute;
GRANT EXECUTE ON FUNCTION store_organism(character varying, character varying, character varying)  TO chacrm_execute;
GRANT EXECUTE ON FUNCTION store_regtype(integer, character varying)  TO chacrm_execute;
GRANT EXECUTE ON FUNCTION store_transformant(integer, character varying, character varying)  TO chacrm_execute;
GRANT EXECUTE ON FUNCTION store_transformant_image_location(integer)  TO chacrm_execute;
GRANT EXECUTE ON FUNCTION store_transformant_image_location(integer, character varying, integer, character varying)  TO chacrm_execute;
GRANT EXECUTE ON FUNCTION subsequence(integer, integer, integer, integer)  TO chacrm_execute;
GRANT EXECUTE ON FUNCTION subsequence_by_feature(integer, integer, integer)  TO chacrm_execute;
GRANT EXECUTE ON FUNCTION subsequence_by_feature(integer)  TO chacrm_execute;
GRANT EXECUTE ON FUNCTION subsequence_by_featureloc(integer)  TO chacrm_execute;
GRANT EXECUTE ON FUNCTION subsequence_by_subfeatures(integer, integer, integer, integer)  TO chacrm_execute;
GRANT EXECUTE ON FUNCTION subsequence_by_subfeatures(integer, integer)  TO chacrm_execute;
GRANT EXECUTE ON FUNCTION subsequence_by_subfeatures(integer)  TO chacrm_execute;
GRANT EXECUTE ON FUNCTION subsequence_by_typed_subfeatures(integer, integer, integer, integer)  TO chacrm_execute;
GRANT EXECUTE ON FUNCTION subsequence_by_typed_subfeatures(integer, integer)  TO chacrm_execute;
GRANT EXECUTE ON FUNCTION translate_dna(text, integer)  TO chacrm_execute;
GRANT EXECUTE ON FUNCTION _fill_cvtermpath4node(integer, integer, integer, integer, integer)  TO chacrm_execute;
GRANT EXECUTE ON FUNCTION _fill_cvtermpath4node2detect_cycle(integer, integer, integer, integer, integer)  TO chacrm_execute;
GRANT EXECUTE ON FUNCTION _fill_cvtermpath4root(integer, integer)  TO chacrm_execute;
GRANT EXECUTE ON FUNCTION _fill_cvtermpath4root2detect_cycle(integer, integer)  TO chacrm_execute;
GRANT EXECUTE ON FUNCTION _fill_cvtermpath4soi(integer, integer)  TO chacrm_execute;
GRANT EXECUTE ON FUNCTION _fill_cvtermpath4soinode(integer, integer, integer, integer, integer)  TO chacrm_execute;
GRANT EXECUTE ON FUNCTION _get_all_object_ids(integer)  TO chacrm_execute;
GRANT EXECUTE ON FUNCTION _get_all_subject_ids(integer)  TO chacrm_execute;
GRANT EXECUTE ON FUNCTION boxquery(integer, integer)  TO chacrm_execute;
GRANT EXECUTE ON FUNCTION boxrange(integer, integer)  TO chacrm_execute;
GRANT EXECUTE ON FUNCTION cache_all_fragment_residues()  TO chacrm_execute;
GRANT EXECUTE ON FUNCTION cache_all_fragment_residues(integer)  TO chacrm_execute;
GRANT EXECUTE ON FUNCTION chado_args_init()  TO chacrm_execute;
GRANT EXECUTE ON FUNCTION complement_residues(text)  TO chacrm_execute;
GRANT EXECUTE ON FUNCTION concat_pair(text, text)  TO chacrm_execute;
GRANT EXECUTE ON FUNCTION create_point(integer, integer)  TO chacrm_execute;
GRANT EXECUTE ON FUNCTION create_soi()  TO chacrm_execute;
GRANT EXECUTE ON FUNCTION delete_analysis_features(integer, integer)  TO chacrm_execute;
GRANT EXECUTE ON FUNCTION feature_disjoint_from(integer)  TO chacrm_execute;
GRANT EXECUTE ON FUNCTION feature_intersecting(integer)  TO chacrm_execute;
GRANT EXECUTE ON FUNCTION feature_overlaps(integer)  TO chacrm_execute;
GRANT EXECUTE ON FUNCTION feature_slice(integer, integer)  TO chacrm_execute;
GRANT EXECUTE ON FUNCTION feature_slice(character varying, integer, integer)  TO chacrm_execute;
GRANT EXECUTE ON FUNCTION feature_slice(integer, integer, integer)  TO chacrm_execute;
GRANT EXECUTE ON FUNCTION feature_subalignments(integer) TO chacrm_execute;
GRANT EXECUTE ON FUNCTION featureloc_slice(integer, integer, integer) TO chacrm_execute;
GRANT EXECUTE ON FUNCTION featureloc_slice(character varying, integer, integer) TO chacrm_execute;
GRANT EXECUTE ON FUNCTION featureloc_slice(integer, integer) TO chacrm_execute;
GRANT EXECUTE ON FUNCTION featureslice(integer, integer) TO chacrm_execute;
GRANT EXECUTE ON FUNCTION fill_cvtermpath(integer)  TO chacrm_execute;
GRANT EXECUTE ON FUNCTION fill_cvtermpath(character varying)  TO chacrm_execute;
GRANT EXECUTE ON FUNCTION foo(integer)  TO chacrm_execute;
GRANT EXECUTE ON FUNCTION get_all_object_ids(integer)  TO chacrm_execute;
GRANT EXECUTE ON FUNCTION get_all_subject_ids(integer)  TO chacrm_execute;
GRANT EXECUTE ON FUNCTION get_cv_id_for_feature()  TO chacrm_execute;
GRANT EXECUTE ON FUNCTION get_cv_id_for_feature_relationsgip()  TO chacrm_execute;
GRANT EXECUTE ON FUNCTION get_cv_id_for_feature_relationship()  TO chacrm_execute;
GRANT EXECUTE ON FUNCTION get_cv_id_for_featureprop()  TO chacrm_execute;
GRANT EXECUTE ON FUNCTION get_cv_id_for_relation()  TO chacrm_execute;
GRANT EXECUTE ON FUNCTION get_cvterm_id_for_is_a()  TO chacrm_execute;
GRANT EXECUTE ON FUNCTION get_cycle_cvterm_id(integer, integer)  TO chacrm_execute;
GRANT EXECUTE ON FUNCTION get_cycle_cvterm_id(integer)  TO chacrm_execute;
GRANT EXECUTE ON FUNCTION get_cycle_cvterm_id(character varying)  TO chacrm_execute;
GRANT EXECUTE ON FUNCTION get_cycle_cvterm_ids(integer)  TO chacrm_execute;
GRANT EXECUTE ON FUNCTION get_feature_id(character varying, character varying, character varying)  TO chacrm_execute;
GRANT EXECUTE ON FUNCTION get_feature_ids(text)  TO chacrm_execute;
GRANT EXECUTE ON FUNCTION get_feature_ids_by_child_count(character varying, character varying, integer, character varying, character)  TO chacrm_execute;
GRANT EXECUTE ON FUNCTION get_feature_ids_by_ont(character varying, character varying)  TO chacrm_execute;
GRANT EXECUTE ON FUNCTION get_feature_ids_by_ont_root(character varying, character varying)  TO chacrm_execute;
GRANT EXECUTE ON FUNCTION get_feature_ids_by_property(character varying, character varying)  TO chacrm_execute;
GRANT EXECUTE ON FUNCTION get_feature_ids_by_propval(character varying)  TO chacrm_execute;
GRANT EXECUTE ON FUNCTION get_feature_ids_by_type(character varying, character)  TO chacrm_execute;
GRANT EXECUTE ON FUNCTION get_feature_ids_by_type_name(character varying, text, character)  TO chacrm_execute;
GRANT EXECUTE ON FUNCTION get_feature_ids_by_type_src(character varying, text, character)  TO chacrm_execute;
GRANT EXECUTE ON FUNCTION get_feature_relationship_type_id(character varying)  TO chacrm_execute;
GRANT EXECUTE ON FUNCTION get_feature_type_id(character varying)  TO chacrm_execute;
GRANT EXECUTE ON FUNCTION get_featureprop_type_id(character varying)  TO chacrm_execute;
GRANT EXECUTE ON FUNCTION get_gene_synonyms(text)  TO chacrm_execute;
GRANT EXECUTE ON FUNCTION get_graph_above(integer)  TO chacrm_execute;
GRANT EXECUTE ON FUNCTION get_graph_below(integer)  TO chacrm_execute;
GRANT EXECUTE ON FUNCTION get_it_sub_cvterm_ids(text)  TO chacrm_execute;
GRANT EXECUTE ON FUNCTION get_organism_id(character varying)  TO chacrm_execute;
GRANT EXECUTE ON FUNCTION get_organism_id(character varying, character varying)  TO chacrm_execute;
GRANT EXECUTE ON FUNCTION get_organism_id_abbrev(character varying)  TO chacrm_execute;
GRANT EXECUTE ON FUNCTION get_sub_feature_ids(text)  TO chacrm_execute;
GRANT EXECUTE ON FUNCTION get_sub_feature_ids(integer)  TO chacrm_execute;
GRANT EXECUTE ON FUNCTION get_sub_feature_ids(integer, integer)  TO chacrm_execute;
GRANT EXECUTE ON FUNCTION get_sub_feature_ids_by_type_src(character varying, text, character)  TO chacrm_execute;
GRANT EXECUTE ON FUNCTION get_up_feature_ids(integer)  TO chacrm_execute;
GRANT EXECUTE ON FUNCTION get_up_feature_ids(text)  TO chacrm_execute;
GRANT EXECUTE ON FUNCTION get_up_feature_ids(integer, integer)  TO chacrm_execute;
GRANT EXECUTE ON FUNCTION order_exons(integer)  TO chacrm_execute;
GRANT EXECUTE ON FUNCTION p(integer, integer)  TO chacrm_execute;
GRANT EXECUTE ON FUNCTION plpgsql_call_handler()  TO chacrm_execute;
GRANT EXECUTE ON FUNCTION project_featureloc_up(integer, integer)  TO chacrm_execute;
GRANT EXECUTE ON FUNCTION project_point_down(integer, integer, integer, integer)  TO chacrm_execute;
GRANT EXECUTE ON FUNCTION project_point_up(integer, integer, integer, integer)  TO chacrm_execute;
GRANT EXECUTE ON FUNCTION r4_map(character varying, integer)  TO chacrm_execute;
GRANT EXECUTE ON FUNCTION r5_map(character varying, integer)  TO chacrm_execute;
GRANT EXECUTE ON FUNCTION remove_transformant_image_location(character varying, character varying)  TO chacrm_execute;
GRANT EXECUTE ON FUNCTION reverse_complement(text)  TO chacrm_execute;
GRANT EXECUTE ON FUNCTION reverse_string(text)  TO chacrm_execute;
GRANT EXECUTE ON FUNCTION share_exons()  TO chacrm_execute;
GRANT EXECUTE ON FUNCTION store_analysis(character varying, character varying, character varying)  TO chacrm_execute;
GRANT EXECUTE ON FUNCTION store_analysisfeature(integer, integer, integer, integer, integer, integer, character varying, character varying, integer, boolean, integer, double precision, double precision, double precision, double precision)  TO chacrm_execute;
GRANT EXECUTE ON FUNCTION store_db(character varying)  TO chacrm_execute;
GRANT EXECUTE ON FUNCTION store_dbxref(character varying, character varying)  TO chacrm_execute;
GRANT EXECUTE ON FUNCTION store_feature(integer, integer, integer, integer, integer, integer, character varying, character varying, integer, boolean)  TO chacrm_execute;
GRANT EXECUTE ON FUNCTION store_feature_dbxref(integer, character varying, character varying)  TO chacrm_execute;
GRANT EXECUTE ON FUNCTION store_feature_synonym(integer, character varying, integer, boolean, boolean, integer)  TO chacrm_execute;
GRANT EXECUTE ON FUNCTION store_featureloc(integer, integer, integer, integer, integer, integer, integer)  TO chacrm_execute;
GRANT EXECUTE ON FUNCTION store_featureprop(integer, character varying, character varying, integer)  TO chacrm_execute;
GRANT EXECUTE ON FUNCTION store_featureprop(character varying, character varying, integer)  TO chacrm_execute;
GRANT EXECUTE ON FUNCTION store_featureprop(integer, character varying, character varying)  TO chacrm_execute;
GRANT EXECUTE ON FUNCTION store_organism(character varying, character varying, character varying)  TO chacrm_execute;
GRANT EXECUTE ON FUNCTION store_organism(character varying, character varying)  TO chacrm_execute;
GRANT EXECUTE ON FUNCTION store_regtype(integer, character varying)  TO chacrm_execute;
GRANT EXECUTE ON FUNCTION store_transformant(integer, character varying, character varying)  TO chacrm_execute;
GRANT EXECUTE ON FUNCTION store_transformant_image_location(integer, character varying, integer, character varying)  TO chacrm_execute;
GRANT EXECUTE ON FUNCTION store_transformant_image_location(integer)  TO chacrm_execute;
GRANT EXECUTE ON FUNCTION subsequence(integer, integer, integer, integer)  TO chacrm_execute;
GRANT EXECUTE ON FUNCTION subsequence_by_feature(integer, integer, integer)  TO chacrm_execute;
GRANT EXECUTE ON FUNCTION subsequence_by_feature(integer)  TO chacrm_execute;
GRANT EXECUTE ON FUNCTION subsequence_by_featureloc(integer)  TO chacrm_execute;
GRANT EXECUTE ON FUNCTION subsequence_by_subfeatures(integer, integer, integer, integer)  TO chacrm_execute;
GRANT EXECUTE ON FUNCTION subsequence_by_subfeatures(integer, integer)  TO chacrm_execute;
GRANT EXECUTE ON FUNCTION subsequence_by_subfeatures(integer)  TO chacrm_execute;
GRANT EXECUTE ON FUNCTION subsequence_by_typed_subfeatures(integer, integer, integer, integer)  TO chacrm_execute;
GRANT EXECUTE ON FUNCTION subsequence_by_typed_subfeatures(integer, integer)  TO chacrm_execute;
GRANT EXECUTE ON FUNCTION translate_dna(text, integer)  TO chacrm_execute;
