mysql -h mysql1 -u wikiAdmin -pwikiAdmin wiki -e "call updateUsername('smithr','smithro')"
mysql -h mysql1 -u wikiAdmin -pwikiAdmin wiki -e "call updateUsername('harrisa','harrisal')"
mysql -h mysql1 -u wikiAdmin -pwikiAdmin wiki -e "call updateUsername('andersond','andersonda')"
mysql -h mysql1 -u wikiAdmin -pwikiAdmin wiki -e "call updateUsername('leea','leeal')"
mysql -h mysql1 -u wikiAdmin -pwikiAdmin wiki -e "call updateUsername('leet','leetz')"
# mysql -h mysql1 -u wikiAdmin -pwikiAdmin wiki -e "call updateUsername('liuj','liujin')"
mysql -h mysql1 -u wikiAdmin -pwikiAdmin wiki -e "call updateUsername('morrisl','morrisli')"
mysql -h mysql1 -u wikiAdmin -pwikiAdmin wiki -e "call updateUsername('mcgowank','mcgowanke')"
mysql -h mysql1 -u wikiAdmin -pwikiAdmin wiki -e "call updateUsername('tangj','tangji')"
mysql -h mysql1 -u wikiAdmin -pwikiAdmin wiki -e "call updateUsername('xiej','xiejun')"
mysql -h mysql1 -u wikiAdmin -pwikiAdmin wiki -e "call updateUsername('yuh','yuhu')"
# mysql -h mysql1 -u wikiAdmin -pwikiAdmin wiki -e "call updateUsername('zhangx','zhangxioro')"
mysql -h mysql1 -u wikiAdmin -pwikiAdmin wiki -e "call updateUsername('zhangz','zhangzhr')"
